CREATE TABLE "hazard-communication-app_persona" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"roleDescription" text NOT NULL,
	"evaluationInstructions" text NOT NULL,
	"initials" varchar(8) NOT NULL,
	"avatarColor" varchar(64) NOT NULL,
	"imagePath" varchar(512),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hazard-communication-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hazard-communication-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hazard-communication-app_scenario_hazard" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"scenarioId" uuid NOT NULL,
	"hazardTitle" varchar(256) NOT NULL,
	"hazardDescription" text NOT NULL,
	"controlDescription" text NOT NULL,
	"locationNote" text,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hazard-communication-app_scenario_persona" (
	"scenarioId" uuid NOT NULL,
	"personaId" varchar(64) NOT NULL,
	CONSTRAINT "hazard-communication-app_scenario_persona_scenarioId_personaId_pk" PRIMARY KEY("scenarioId","personaId")
);
--> statement-breakpoint
CREATE TABLE "hazard-communication-app_scenario" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"imageFileName" varchar(256) NOT NULL,
	"status" varchar(16) DEFAULT 'draft' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "hazard-communication-app_scenario_hazard" ADD CONSTRAINT "hazard-communication-app_scenario_hazard_scenarioId_hazard-communication-app_scenario_id_fk" FOREIGN KEY ("scenarioId") REFERENCES "public"."hazard-communication-app_scenario"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hazard-communication-app_scenario_persona" ADD CONSTRAINT "hazard-communication-app_scenario_persona_scenarioId_hazard-communication-app_scenario_id_fk" FOREIGN KEY ("scenarioId") REFERENCES "public"."hazard-communication-app_scenario"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hazard-communication-app_scenario_persona" ADD CONSTRAINT "hazard-communication-app_scenario_persona_personaId_hazard-communication-app_persona_id_fk" FOREIGN KEY ("personaId") REFERENCES "public"."hazard-communication-app_persona"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "hazard-communication-app_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "scenario_hazard_scenario_idx" ON "hazard-communication-app_scenario_hazard" USING btree ("scenarioId");--> statement-breakpoint
CREATE INDEX "scenario_persona_scenario_idx" ON "hazard-communication-app_scenario_persona" USING btree ("scenarioId");--> statement-breakpoint
CREATE INDEX "scenario_status_idx" ON "hazard-communication-app_scenario" USING btree ("status");